<!DOCTYPE html>
<html class="dark" lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>InterviewPrep | Elevate Your Technical Career</title>
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        .hero-glow {
            background: radial-gradient(circle at 50% 50%, rgba(103, 80, 164, 0.15) 0%, transparent 50%);
        }
        .grid-bg {
            background-image: linear-gradient(to right, rgba(255,255,255,0.05) 1px, transparent 1px),
                              linear-gradient(to bottom, rgba(255,255,255,0.05) 1px, transparent 1px);
            background-size: 40px 40px;
        }
    </style>
</head>
<body class="bg-background text-on-background selection:bg-primary-container selection:text-on-primary-container antialiased overflow-x-hidden">
    {{-- Header --}}
    <header class="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-md border-b border-outline-variant/30">
        <div class="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
            <div class="flex items-center gap-sm">
                <div class="w-10 h-10 rounded-xl bg-gradient-to-br from-primary-container to-secondary-container flex items-center justify-center text-on-primary-container font-bold text-xl shadow-lg shadow-primary/20">
                    IP
                </div>
                <span class="font-display text-xl font-bold tracking-tight text-on-surface">InterviewPrep</span>
            </div>

            <nav class="hidden md:flex items-center gap-xl text-body-sm font-medium text-on-surface-variant">
                <a href="#features" class="hover:text-primary transition-colors">Features</a>
                <a href="#how-it-works" class="hover:text-primary transition-colors">How it works</a>
                <a href="https://github.com/wissalaitihya/InterviewPrep" target="_blank" class="hover:text-primary transition-colors">Open Source</a>
            </nav>

            <div class="flex items-center gap-md">
                @auth
                    <a href="{{ url('/dashboard') }}" class="btn-primary flex items-center gap-sm">
                        Go to Dashboard
                        <span class="material-symbols-outlined text-[18px]">arrow_forward</span>
                    </a>
                @else
                    <a href="{{ route('login') }}" class="btn-ghost px-lg">Log in</a>
                    <a href="{{ route('register') }}" class="btn-primary">Get Started</a>
                @endauth
            </div>
        </div>
    </header>

    <main class="relative pt-32">
        {{-- Background Effects --}}
        <div class="absolute inset-0 -z-10 grid-bg [mask-image:radial-gradient(ellipse_at_center,black,transparent)]"></div>
        <div class="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[800px] -z-10 hero-glow"></div>

        {{-- Hero Section --}}
        <section class="max-w-7xl mx-auto px-6 py-20 text-center">
            <div class="inline-flex items-center gap-sm px-md py-xs rounded-full bg-primary/10 border border-primary/20 text-primary text-label-caps font-semibold mb-lg animate-slide-in">
                <span class="material-symbols-outlined text-[16px]" style="font-variation-settings: 'FILL' 1;">auto_awesome</span>
                Now powered by Groq AI
            </div>
            
            <h1 class="font-display text-5xl md:text-7xl font-bold tracking-tight text-on-surface mb-xl max-w-4xl mx-auto leading-[1.1]">
                Master the technical interview with <span class="ai-gradient-text">AI intelligence.</span>
            </h1>
            
            <p class="text-on-surface-variant text-body-lg max-w-2xl mx-auto mb-2xl leading-relaxed">
                Elevate your preparation with targeted questions generated by AI based on your revision notes. Track your mastery across domains and land your dream role.
            </p>

            <div class="flex flex-col sm:flex-row items-center justify-center gap-md mb-32">
                <a href="{{ route('register') }}" class="btn-primary h-14 px-xl flex items-center justify-center text-body-lg gap-sm w-full sm:w-auto">
                    Start Prep Now
                    <span class="material-symbols-outlined text-[20px]">rocket_launch</span>
                </a>
                <a href="#features" class="btn-ghost h-14 px-xl flex items-center justify-center text-body-lg w-full sm:w-auto">
                    Explore Features
                </a>
            </div>

            {{-- Mockup --}}
            <div class="relative max-w-5xl mx-auto">
                <div class="absolute -inset-1 bg-gradient-to-r from-primary to-secondary rounded-3xl blur opacity-20 group-hover:opacity-40 transition duration-1000"></div>
                <div class="relative glass-panel rounded-3xl overflow-hidden border border-outline-variant/50 shadow-2xl">
                    <div class="bg-surface-container-low h-12 flex items-center px-lg gap-sm border-b border-outline-variant/30">
                        <div class="flex gap-1.5">
                            <div class="w-3 h-3 rounded-full bg-error/40"></div>
                            <div class="w-3 h-3 rounded-full bg-tertiary/40"></div>
                            <div class="w-3 h-3 rounded-full bg-primary/40"></div>
                        </div>
                        <div class="flex-1 bg-surface-container-lowest rounded-lg h-7 mx-md border border-outline-variant/20 flex items-center px-md text-[11px] text-on-surface-variant/40">
                            interview-prep.app/dashboard
                        </div>
                    </div>
                    <div class="p-lg md:p-xl bg-surface-container-lowest">
                        <div class="grid grid-cols-1 md:grid-cols-3 gap-lg">
                            <div class="glass-panel p-lg rounded-2xl border-outline-variant/30 h-40"></div>
                            <div class="glass-panel p-lg rounded-2xl border-outline-variant/30 h-40"></div>
                            <div class="glass-panel p-lg rounded-2xl border-outline-variant/30 h-40"></div>
                            <div class="md:col-span-2 glass-panel p-lg rounded-2xl border-outline-variant/30 h-64"></div>
                            <div class="glass-panel p-lg rounded-2xl border-outline-variant/30 h-64"></div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        {{-- Features Section --}}
        <section id="features" class="max-w-7xl mx-auto px-6 py-32 border-t border-outline-variant/30">
            <div class="grid grid-cols-1 md:grid-cols-3 gap-xl">
                <div class="space-y-md">
                    <div class="w-12 h-12 rounded-2xl bg-primary/10 flex items-center justify-center text-primary">
                        <span class="material-symbols-outlined text-[28px]" style="font-variation-settings: 'FILL' 1;">auto_awesome</span>
                    </div>
                    <h3 class="font-h3 text-h3 text-on-surface">AI Generation</h3>
                    <p class="text-on-surface-variant text-body-md leading-relaxed">
                        Groq AI analyzes your notes and generates context-aware interview questions to test your depth of knowledge.
                    </p>
                </div>
                <div class="space-y-md">
                    <div class="w-12 h-12 rounded-2xl bg-secondary/10 flex items-center justify-center text-secondary">
                        <span class="material-symbols-outlined text-[28px]" style="font-variation-settings: 'FILL' 1;">category</span>
                    </div>
                    <h3 class="font-h3 text-h3 text-on-surface">Domain Mastery</h3>
                    <p class="text-on-surface-variant text-body-md leading-relaxed">
                        Organize concepts into domains like Backend, Frontend, or DevOps. Track your progress with visual mastery rates.
                    </p>
                </div>
                <div class="space-y-md">
                    <div class="w-12 h-12 rounded-2xl bg-tertiary/10 flex items-center justify-center text-tertiary">
                        <span class="material-symbols-outlined text-[28px]" style="font-variation-settings: 'FILL' 1;">analytics</span>
                    </div>
                    <h3 class="font-h3 text-h3 text-on-surface">Study Insights</h3>
                    <p class="text-on-surface-variant text-body-md leading-relaxed">
                        Keep track of your study streaks and revision frequency to ensure you stay prepared for any surprise interview.
                    </p>
                </div>
            </div>
        </section>

        {{-- CTA Section --}}
        <section class="max-w-7xl mx-auto px-6 py-32">
            <div class="relative glass-panel rounded-3xl p-12 md:p-24 overflow-hidden text-center">
                <div class="absolute inset-0 bg-gradient-to-br from-primary/10 to-secondary/10 -z-10"></div>
                <h2 class="font-display text-4xl md:text-5xl font-bold tracking-tight text-on-surface mb-md max-w-2xl mx-auto">
                    Ready to crush your next interview?
                </h2>
                <p class="text-on-surface-variant text-body-lg max-w-xl mx-auto mb-xl leading-relaxed">
                    Join hundreds of developers using InterviewPrep to master their technical knowledge.
                </p>
                <a href="{{ route('register') }}" class="btn-primary h-14 px-xl inline-flex items-center justify-center text-body-lg gap-sm">
                    Create Your Account
                    <span class="material-symbols-outlined text-[20px]">chevron_right</span>
                </a>
            </div>
        </section>
    </main>

    {{-- Footer --}}
    <footer class="border-t border-outline-variant/30 py-20 bg-surface-container-low/30">
        <div class="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between gap-xl">
            <div class="space-y-md">
                <div class="flex items-center gap-sm">
                    <div class="w-8 h-8 rounded-lg bg-primary-container flex items-center justify-center text-on-primary-container font-bold text-lg">
                        IP
                    </div>
                    <span class="font-display text-lg font-bold tracking-tight text-on-surface">InterviewPrep</span>
                </div>
                <p class="text-on-surface-variant text-body-sm max-w-xs">
                    The ultimate companion for technical interview preparation. Built for developers, by developers.
                </p>
            </div>
            
            <div class="grid grid-cols-2 gap-xl">
                <div class="space-y-sm">
                    <h4 class="text-label-caps font-semibold text-on-surface">Product</h4>
                    <ul class="space-y-xs text-body-sm text-on-surface-variant">
                        <li><a href="#features" class="hover:text-primary transition-colors">Features</a></li>
                        <li><a href="{{ route('login') }}" class="hover:text-primary transition-colors">Login</a></li>
                    </ul>
                </div>
                <div class="space-y-sm">
                    <h4 class="text-label-caps font-semibold text-on-surface">Community</h4>
                    <ul class="space-y-xs text-body-sm text-on-surface-variant">
                        <li><a href="https://github.com/wissalaitihya/InterviewPrep" target="_blank" class="hover:text-primary transition-colors">GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="max-w-7xl mx-auto px-6 mt-20 pt-10 border-t border-outline-variant/10 text-on-surface-variant text-[11px] flex justify-between">
            <p>&copy; {{ date('Y') }} InterviewPrep. All rights reserved.</p>
            <p>Built with Laravel & Groq AI</p>
        </div>
    </footer>
</body>
</html>
